version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server

  loan-service:
    build: ./loan-service
    container_name: loan-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server

  card-service:
    build: ./card-service
    container_name: card-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - eureka-server
    environment:
      MAIL_USERNAME: your-email@gmail.com
      MAIL_PASSWORD: your-app-password

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - eureka-server

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - eureka-server

  email-service:
    build: ./email-service
    container_name: email-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    environment:
      MAIL_USERNAME: your-email@gmail.com
      MAIL_PASSWORD: your-app-password

volumes:
  postgres_data: