server:
  port: 8084

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka