spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://spectacular-optimism-production-55b6.up.railway.app"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

            allowedHeaders: "*"

            allowCredentials: true

      routes:

        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: account
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**