server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/loans/**

        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/api/cards/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

    management:
      endpoints:
        web:
          exposure:
            include: gateway,health

    logging:
      level:
        org.springframework.cloud.gateway: TRACE