server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://postgres:5432/account_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

  mvc:
    static-path-pattern: /**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    hostname: account-service
    prefer-ip-address: false