server:
  port: ${PORT:8081}

spring:
  application:
    name: account-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://digital-banking-system-production-2f87.up.railway.app/eureka/

  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30