server:
  port: 8082

spring:
  application:
    name: loan-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-lazp.onrender.com/eureka/

  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}