server:
  port: 8083

spring:
  application:
    name: card-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://postgres:5432/card_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health

logging:
  level:
    org.springframework.cloud.gateway: TRACE