server:
  port: 8083

spring:
  application:
    name: card-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-lazp.onrender.com/eureka/
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: gateway,health

logging:
  level:
    org.springframework.cloud.gateway: TRACE