server:
  port: 8086

spring:
  application:
    name: loan-service

  datasource:
    url: jdbc:postgresql://ep-snowy-recipe-av4429cf-pooler.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_XpJGQHE46AIt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-lazp.onrender.com/eureka/