server:
  port: 8086

spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: sharmashubham05275@gmail.com
    password: eyoy gdhr ripw ghlk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/